export const categories = [
	{ label: 'Undergraduate', value: 'undergraduate' },
	{ label: 'Graduate', value: 'graduate' },
	{ label: 'Certificate', value: 'certificate' },
	{ label: 'None', value: 'none' },
];

export const short_names = [
	{ label: 'BBA', value: 'bba' },
	{ label: 'BSc CSE', value: 'bsc-cse' },
	{ label: 'BSc Textile', value: 'bsc-textile' },
	{ label: 'BSc Mechanical', value: 'bsc-mechanical' },
	{ label: 'BSc IP', value: 'bsc-ip' },
	{ label: 'BSc EEE', value: 'bsc-eee' },
	{ label: 'BSc Civil', value: 'bsc-civil' },
	{ label: 'EMBA', value: 'emba' },
	{ label: 'MBA', value: 'mba' },
	{ label: 'MBA One Year', value: 'mba-one-year' },
	{ label: 'THM', value: 'thm' },
	{ label: 'BA English', value: 'ba-english' },
	{ label: 'BSS Economics', value: 'bss-economics' },
	{ label: 'LLB', value: 'llb' },
	{ label: 'LLM', value: 'llm' },
	{ label: 'MA English', value: 'ma-english' },
	{ label: 'MA English 2 Year', value: 'ma-english-two-year' },
	{ label: 'MGDS One Year', value: 'mgds-one-year' },
	{ label: 'MSS Economics', value: 'mss-economics' },
	{ label: 'Physics', value: 'physics' },
	{ label: 'Mathematics', value: 'mathematics' },
	{ label: 'Chemistry', value: 'chemistry' },
	{ label: 'Extra Curricular Club', value: 'extra-curricular-club' },
];
